name: store_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  gap: ^3.0.1
  cached_network_image: ^3.4.1
  provider: ^6.0.5
  skeletonizer: ^2.1.0+1
  smooth_page_indicator: ^1.2.1
  font_awesome_flutter: ^10.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: ReadexPro
      fonts:
        - asset: assets/fonts/ReadexPro-Regular.ttf
        - asset: assets/fonts/ReadexPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/ReadexPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ReadexPro-Bold.ttf
          weight: 700
